{
  "info": {
    "_postman_id": "2657417-23eb51f6-0821-da7c-f2ef-1eb06d2a16b0",
    "name": "Everest Backend Structure",
    "description": "Documentation:  https://wiki.viessmann.com/display/VPL/Everest+Postman+Collections",
    "schema": "https://schema.getpostman.com/json/collection/v2.0.0/collection.json"
  },
  "item": [
    {
      "_postman_id": "2657417-65578a87-9da2-4dd3-12ef-b939b93f80e8",
      "name": "Monitor",
      "description": null,
      "item": [
        {
          "_postman_id": "2657417-c0120f67-4a97-8998-ba36-2eb4ec3417fb",
          "name": "backend",
          "description": "Folder for backend",
          "item": [
            {
              "_postman_id": "2657417-1653bfe2-faa8-5dd9-1051-3ef2f3bf81b0",
              "name": "Get monitor main entry point view",
              "request": {
                "method": "GET",
                "header": [
                  {
                    "key": "Authorization",
                    "value": "{{oauth2}}"
                  },
                  {
                    "key": "Accept",
                    "value": "application/vnd.siren+json, application/json"
                  },
                  {
                    "key": "Content-Type",
                    "value": "application/json"
                  }
                ],
                "body": {
                  "mode": "raw",
                  "raw": ""
                },
                "url": "http://{{url}}:18083/backend/monitor/overview",
                "description": "Returns list of subentities pointing to buildings and invitations"
              },
              "response": []
            },
            {
              "_postman_id": "2657417-f798d4ec-8e44-5029-16fb-037fd188433c",
              "name": "Get installation details",
              "request": {
                "method": "GET",
                "header": [
                  {
                    "key": "Authorization",
                    "value": "{{oauth2}}"
                  },
                  {
                    "key": "Accept",
                    "value": "application/vnd.siren+json, application/json"
                  },
                  {
                    "key": "Content-Type",
                    "value": "application/json"
                  }
                ],
                "body": {
                  "mode": "raw",
                  "raw": ""
                },
                "url": "http://{{url}}:18083/backend/monitor/installations/{{installationId}}/components",
                "description": "Returns installation details by given installationID"
              },
              "response": []
            },
            {
              "_postman_id": "2657417-0da7666d-b320-5cfc-a890-08a32e0a9642",
              "name": "Get installation circuit details",
              "request": {
                "method": "GET",
                "header": [
                  {
                    "key": "Authorization",
                    "value": "{{oauth2}}"
                  },
                  {
                    "key": "Accept",
                    "value": "application/vnd.siren+json, application/json"
                  },
                  {
                    "key": "Content-Type",
                    "value": "application/json"
                  }
                ],
                "body": {
                  "mode": "raw",
                  "raw": ""
                },
                "url": {
                  "raw": "http://{{url}}:18083/backend/monitor/installations/{{installationId}}/gateways/{{gatewaySerial}}/heating-devices/{{pairingId}}/heating-circuits/:circuitId",
                  "protocol": "http",
                  "host": [
                    "{{url}}"
                  ],
                  "port": "18083",
                  "path": [
                    "backend",
                    "monitor",
                    "installations",
                    "{{installationId}}",
                    "gateways",
                    "{{gatewaySerial}}",
                    "heating-devices",
                    "{{pairingId}}",
                    "heating-circuits",
                    ":circuitId"
                  ],
                  "variable": [
                    {
                      "key": "installationId",
                      "value": "{{installationId}}"
                    },
                    {
                      "key": "gatewaySerial",
                      "value": "{{gatewaySerial}}"
                    },
                    {
                      "key": "pairingId",
                      "value": "{{pairingId}}"
                    },
                    {
                      "key": "circuitId",
                      "value": "{{circuitId}}"
                    }
                  ]
                },
                "description": "Returns circuit details by given installationID, gatewaySerial, pairingId and circuitId"
              },
              "response": []
            },
            {
              "_postman_id": "2657417-4980e3fa-d513-4968-e847-16fae2454286",
              "name": "Get buildings",
              "request": {
                "method": "GET",
                "header": [
                  {
                    "key": "Authorization",
                    "value": "{{oauth2}}"
                  },
                  {
                    "key": "Accept",
                    "value": "application/vnd.siren+json, application/json"
                  },
                  {
                    "key": "Content-Type",
                    "value": "application/json"
                  }
                ],
                "body": {
                  "mode": "raw",
                  "raw": ""
                },
                "url": {
                  "raw": "http://{{url}}:18083/backend/monitor/companies/{{customerNumber}}/buildings",
                  "protocol": "http",
                  "host": [
                    "{{url}}"
                  ],
                  "port": "18083",
                  "path": [
                    "backend",
                    "monitor",
                    "companies",
                    "{{customerNumber}}",
                    "buildings"
                  ],
                  "variable": [
                    {
                      "key": "customerNumber",
                      "value": "{{customerNumber}}"
                    }
                  ]
                },
                "description": "Returns a list of buildings by given customerNumber"
              },
              "response": []
            },
            {
              "_postman_id": "2657417-12e68675-a1dd-16e8-a152-68a7b0d7b7c9",
              "name": "Get building details",
              "request": {
                "method": "GET",
                "header": [
                  {
                    "key": "Authorization",
                    "value": "{{oauth2}}"
                  },
                  {
                    "key": "Accept",
                    "value": "application/vnd.siren+json, application/json"
                  },
                  {
                    "key": "Content-Type",
                    "value": "application/json"
                  }
                ],
                "body": {
                  "mode": "raw",
                  "raw": ""
                },
                "url": "http://{{url}}:18083/backend/monitor/companies/{{customerNumber}}/buildings/{{buildingId}}/sidenav",
                "description": "Returns building details by given buildingID"
              },
              "response": []
            },
            {
              "_postman_id": "2657417-f2c7472e-b50a-78f5-83ac-72e36b7d63f8",
              "name": "Get domestic hot water target temperature",
              "request": {
                "method": "GET",
                "header": [
                  {
                    "key": "Authorization",
                    "value": "{{oauth2}}"
                  },
                  {
                    "key": "Accept",
                    "value": "application/vnd.siren+json"
                  },
                  {
                    "key": "Content-Type",
                    "value": "application/json"
                  }
                ],
                "body": {
                  "mode": "raw",
                  "raw": ""
                },
                "url": {
                  "raw": "http://{{url}}:18083/backend/monitor/installations/{{installationId}}/domestic-hot-water-tank/temperature",
                  "protocol": "http",
                  "host": [
                    "{{url}}"
                  ],
                  "port": "18083",
                  "path": [
                    "backend",
                    "monitor",
                    "installations",
                    "{{installationId}}",
                    "domestic-hot-water-tank",
                    "temperature"
                  ],
                  "variable": [
                    {
                      "key": "installationId",
                      "value": "{{installationId}}"
                    }
                  ]
                }
              },
              "response": []
            },
            {
              "_postman_id": "2657417-70b7ba27-b480-d086-e3f6-615b58021365",
              "name": "Get monitor dashboard module",
              "request": {
                "method": "GET",
                "header": [
                  {
                    "key": "Authorization",
                    "value": "{{oauth2}}"
                  },
                  {
                    "key": "Accept",
                    "value": "application/vnd.siren+json, application/json"
                  },
                  {
                    "key": "Content-Type",
                    "value": "application/json"
                  }
                ],
                "body": {
                  "mode": "raw",
                  "raw": ""
                },
                "url": {
                  "raw": "http://{{url}}:18083/backend/monitor/users/{{userId}}/dashboard-module-widget/monitoring",
                  "protocol": "http",
                  "host": [
                    "{{url}}"
                  ],
                  "port": "18083",
                  "path": [
                    "backend",
                    "monitor",
                    "users",
                    "{{userId}}",
                    "dashboard-module-widget",
                    "monitoring"
                  ],
                  "variable": [
                    {
                      "key": "userId",
                      "value": "{{userId}}"
                    }
                  ]
                },
                "description": "Returns dashboard module by given userID"
              },
              "response": []
            },
            {
              "_postman_id": "2657417-ad3e6eee-c077-2e95-6e4c-da5b2d94aa5a",
              "name": "Get requested invitation collection",
              "request": {
                "method": "GET",
                "header": [
                  {
                    "key": "Authorization",
                    "value": "{{oauth2}}"
                  },
                  {
                    "key": "Accept",
                    "value": "application/vnd.siren+json"
                  },
                  {
                    "key": "Content-Type",
                    "value": "application/json"
                  }
                ],
                "body": {
                  "mode": "raw",
                  "raw": ""
                },
                "url": {
                  "raw": "http://{{url}}:18083/backend/monitor/users/{{userId}}/invitations/requested",
                  "protocol": "http",
                  "host": [
                    "{{url}}"
                  ],
                  "port": "18083",
                  "path": [
                    "backend",
                    "monitor",
                    "users",
                    "{{userId}}",
                    "invitations",
                    "requested"
                  ],
                  "variable": [
                    {
                      "key": "userId",
                      "value": "{{userId}}"
                    }
                  ]
                },
                "description": "returns requested invitation collection"
              },
              "response": []
            },
            {
              "_postman_id": "2657417-18d54683-f7ba-3f60-e719-f0219a3bbc1e",
              "name": "Get received invitation collection",
              "request": {
                "method": "GET",
                "header": [
                  {
                    "key": "Authorization",
                    "value": "{{oauth2}}"
                  },
                  {
                    "key": "Accept",
                    "value": "application/vnd.siren+json"
                  },
                  {
                    "key": "Content-Type",
                    "value": "application/json"
                  }
                ],
                "body": {
                  "mode": "raw",
                  "raw": ""
                },
                "url": {
                  "raw": "http://{{url}}:18083/backend/monitor/users/{{userId}}/invitations/received",
                  "protocol": "http",
                  "host": [
                    "{{url}}"
                  ],
                  "port": "18083",
                  "path": [
                    "backend",
                    "monitor",
                    "users",
                    "{{userId}}",
                    "invitations",
                    "received"
                  ],
                  "variable": [
                    {
                      "key": "userId",
                      "value": "{{userId}}"
                    }
                  ]
                },
                "description": "returns received invitation collection"
              },
              "response": []
            },
            {
              "_postman_id": "2657417-555ab7a1-c595-97e7-d7a1-9164f123e25c",
              "name": "Update heating schedule",
              "request": {
                "method": "POST",
                "header": [
                  {
                    "key": "Authorization",
                    "value": "{{oauth2}}"
                  },
                  {
                    "key": "Accept",
                    "value": "application/vnd.siren+json, application/json"
                  },
                  {
                    "key": "Content-Type",
                    "value": "application/json"
                  }
                ],
                "body": {
                  "mode": "raw",
                  "raw": ""
                },
                "url": {
                  "raw": "http://{{url}}:18083/backend/monitor/installations/{{installationId}}/heating-circuits/:heatingCircuitsIndex/heating-schedule",
                  "protocol": "http",
                  "host": [
                    "{{url}}"
                  ],
                  "port": "18083",
                  "path": [
                    "backend",
                    "monitor",
                    "installations",
                    "{{installationId}}",
                    "heating-circuits",
                    ":heatingCircuitsIndex",
                    "heating-schedule"
                  ],
                  "variable": [
                    {
                      "key": "installationId",
                      "value": "{{installationId}}"
                    },
                    {
                      "key": "heatingCircuitsIndex",
                      "value": "{{heatingCircuitsIndex}}"
                    }
                  ]
                },
                "description": "Updates the complete heating schedule."
              },
              "response": []
            }
          ],
          "_postman_isSubFolder": true
        }
      ]
    },
    {
      "_postman_id": "2657417-83a82ec3-15b3-0b6f-3199-09479e8f8953",
      "name": "Dashboard",
      "description": null,
      "item": [
        {
          "_postman_id": "2657417-7f292709-6495-4ba3-102c-e19c98f3a8f8",
          "name": "backend",
          "description": "Folder for backend",
          "item": [
            {
              "_postman_id": "2657417-adae7090-f2b8-e047-f18f-c4b27777efa4",
              "name": "Get all module classes",
              "request": {
                "method": "GET",
                "header": [
                  {
                    "key": "Authorization",
                    "value": "{{oauth2}}"
                  },
                  {
                    "key": "Accept",
                    "value": "application/vnd.siren+json, application/json"
                  },
                  {
                    "key": "Content-Type",
                    "value": "application/json"
                  }
                ],
                "body": {
                  "mode": "raw",
                  "raw": ""
                },
                "url": "http://{{url}}:18081/backend/dashboard/module-classes"
              },
              "response": []
            },
            {
              "_postman_id": "2657417-8e6f1bcf-a938-e574-994c-bb4d2089a029",
              "name": "http://{{url}}:18081/backend/dashboard/dashboards/{{dashboardId}}",
              "request": {
                "method": "GET",
                "header": [
                  {
                    "key": "Authorization",
                    "value": "{{oauth2}}"
                  },
                  {
                    "key": "Accept",
                    "value": "application/vnd.siren+json, application/json"
                  },
                  {
                    "key": "Content-Type",
                    "value": "application/json"
                  }
                ],
                "body": {
                  "mode": "raw",
                  "raw": ""
                },
                "url": {
                  "raw": "http://{{url}}:18081/backend/dashboard/dashboards/{{dashboardId}}",
                  "protocol": "http",
                  "host": [
                    "{{url}}"
                  ],
                  "port": "18081",
                  "path": [
                    "backend",
                    "dashboard",
                    "dashboards",
                    "{{dashboardId}}"
                  ],
                  "variable": [
                    {
                      "key": "dashboardId",
                      "value": "{{dashboardId}}"
                    }
                  ]
                }
              },
              "response": []
            },
            {
              "_postman_id": "2657417-0df49cc5-25f6-45bf-78e5-9501101eee47",
              "name": "http://{{url}}:18081/backend/dashboard/dashboards/{{dashboardId}}",
              "request": {
                "method": "PUT",
                "header": [
                  {
                    "key": "Authorization",
                    "value": "{{oauth2}}"
                  },
                  {
                    "key": "Accept",
                    "value": "application/vnd.siren+json, application/json"
                  },
                  {
                    "key": "Content-Type",
                    "value": "application/json"
                  }
                ],
                "body": {
                  "mode": "raw",
                  "raw": ""
                },
                "url": {
                  "raw": "http://{{url}}:18081/backend/dashboard/dashboards/{{dashboardId}}",
                  "protocol": "http",
                  "host": [
                    "{{url}}"
                  ],
                  "port": "18081",
                  "path": [
                    "backend",
                    "dashboard",
                    "dashboards",
                    "{{dashboardId}}"
                  ],
                  "variable": [
                    {
                      "key": "dashboardId",
                      "value": "{{dashboardId}}"
                    }
                  ]
                }
              },
              "response": []
            },
            {
              "_postman_id": "2657417-6e20feff-d966-d140-bc4c-36accc607468",
              "name": "http://{{url}}:18081/backend/dashboard/dashboards/{{dashboardId}}",
              "request": {
                "method": "DELETE",
                "header": [
                  {
                    "key": "Authorization",
                    "value": "{{oauth2}}"
                  },
                  {
                    "key": "Accept",
                    "value": "application/vnd.siren+json, application/json"
                  },
                  {
                    "key": "Content-Type",
                    "value": "application/json"
                  }
                ],
                "body": {
                  "mode": "raw",
                  "raw": ""
                },
                "url": {
                  "raw": "http://{{url}}:18081/backend/dashboard/dashboards/{{dashboardId}}",
                  "protocol": "http",
                  "host": [
                    "{{url}}"
                  ],
                  "port": "18081",
                  "path": [
                    "backend",
                    "dashboard",
                    "dashboards",
                    "{{dashboardId}}"
                  ],
                  "variable": [
                    {
                      "key": "dashboardId",
                      "value": "{{dashboardId}}"
                    }
                  ]
                }
              },
              "response": []
            },
            {
              "_postman_id": "2657417-e0761f9d-8275-2c1c-c778-82f394d9aaff",
              "name": "Get a module classes by ID",
              "request": {
                "method": "GET",
                "header": [
                  {
                    "key": "Authorization",
                    "value": "{{oauth2}}"
                  },
                  {
                    "key": "Accept",
                    "value": "application/vnd.siren+json, application/json"
                  },
                  {
                    "key": "Content-Type",
                    "value": "application/json"
                  }
                ],
                "body": {
                  "mode": "raw",
                  "raw": ""
                },
                "url": {
                  "raw": "http://{{url}}:18081/backend/dashboard/module-classes/{{moduleClassId}}",
                  "protocol": "http",
                  "host": [
                    "{{url}}"
                  ],
                  "port": "18081",
                  "path": [
                    "backend",
                    "dashboard",
                    "module-classes",
                    "{{moduleClassId}}"
                  ],
                  "variable": [
                    {
                      "key": "moduleClassId",
                      "value": "{{moduleClassId}}"
                    }
                  ]
                }
              },
              "response": []
            },
            {
              "_postman_id": "2657417-ef0e0b8e-8096-c148-bdd3-f9de77030c6c",
              "name": "http://{{url}}:18081/backend/dashboard/module-widgets/{{moduleWidgetId}}",
              "request": {
                "method": "GET",
                "header": [
                  {
                    "key": "Authorization",
                    "value": "{{oauth2}}"
                  },
                  {
                    "key": "Accept",
                    "value": "application/vnd.siren+json, application/json"
                  },
                  {
                    "key": "Content-Type",
                    "value": "application/json"
                  }
                ],
                "body": {
                  "mode": "raw",
                  "raw": ""
                },
                "url": {
                  "raw": "http://{{url}}:18081/backend/dashboard/module-widgets/{{moduleWidgetId}}",
                  "protocol": "http",
                  "host": [
                    "{{url}}"
                  ],
                  "port": "18081",
                  "path": [
                    "backend",
                    "dashboard",
                    "module-widgets",
                    "{{moduleWidgetId}}"
                  ],
                  "variable": [
                    {
                      "key": "moduleWidgetId",
                      "value": "{{moduleWidgetId}}"
                    }
                  ]
                }
              },
              "response": []
            },
            {
              "_postman_id": "2657417-ee453727-16c5-1a0f-823a-27ebaeae93df",
              "name": "http://{{url}}:18081/backend/dashboard/module-widgets/{{moduleWidgetId}}",
              "request": {
                "method": "PUT",
                "header": [
                  {
                    "key": "Authorization",
                    "value": "{{oauth2}}"
                  },
                  {
                    "key": "Accept",
                    "value": "application/vnd.siren+json, application/json"
                  },
                  {
                    "key": "Content-Type",
                    "value": "application/json"
                  }
                ],
                "body": {
                  "mode": "raw",
                  "raw": ""
                },
                "url": {
                  "raw": "http://{{url}}:18081/backend/dashboard/module-widgets/{{moduleWidgetId}}",
                  "protocol": "http",
                  "host": [
                    "{{url}}"
                  ],
                  "port": "18081",
                  "path": [
                    "backend",
                    "dashboard",
                    "module-widgets",
                    "{{moduleWidgetId}}"
                  ],
                  "variable": [
                    {
                      "key": "moduleWidgetId",
                      "value": "{{moduleWidgetId}}"
                    }
                  ]
                }
              },
              "response": []
            },
            {
              "_postman_id": "2657417-23d14471-876c-1b05-ad0b-b3deb47e5f86",
              "name": "http://{{url}}:18081/backend/dashboard/module-widgets/{{moduleWidgetId}}",
              "request": {
                "method": "DELETE",
                "header": [
                  {
                    "key": "Authorization",
                    "value": "{{oauth2}}"
                  },
                  {
                    "key": "Accept",
                    "value": "application/vnd.siren+json, application/json"
                  },
                  {
                    "key": "Content-Type",
                    "value": "application/json"
                  }
                ],
                "body": {
                  "mode": "raw",
                  "raw": ""
                },
                "url": {
                  "raw": "http://{{url}}:18081/backend/dashboard/module-widgets/{{moduleWidgetId}}",
                  "protocol": "http",
                  "host": [
                    "{{url}}"
                  ],
                  "port": "18081",
                  "path": [
                    "backend",
                    "dashboard",
                    "module-widgets",
                    "{{moduleWidgetId}}"
                  ],
                  "variable": [
                    {
                      "key": "moduleWidgetId",
                      "value": "{{moduleWidgetId}}"
                    }
                  ]
                }
              },
              "response": []
            },
            {
              "_postman_id": "2657417-5eed4589-7e9b-eda8-8dc2-32e925cfee05",
              "name": "http://{{url}}:18081/backend/dashboard/dashboards/{{dashboardId}}/module-widgets",
              "request": {
                "method": "GET",
                "header": [
                  {
                    "key": "Authorization",
                    "value": "{{oauth2}}"
                  },
                  {
                    "key": "Accept",
                    "value": "application/vnd.siren+json, application/json"
                  },
                  {
                    "key": "Content-Type",
                    "value": "application/json"
                  }
                ],
                "body": {
                  "mode": "raw",
                  "raw": ""
                },
                "url": {
                  "raw": "http://{{url}}:18081/backend/dashboard/dashboards/{{dashboardId}}/module-widgets",
                  "protocol": "http",
                  "host": [
                    "{{url}}"
                  ],
                  "port": "18081",
                  "path": [
                    "backend",
                    "dashboard",
                    "dashboards",
                    "{{dashboardId}}",
                    "module-widgets"
                  ],
                  "variable": [
                    {
                      "key": "dashboardId",
                      "value": "{{dashboardId}}"
                    }
                  ]
                }
              },
              "response": []
            },
            {
              "_postman_id": "2657417-ade63ce1-5e8b-a3a1-f097-55a91f8badfb",
              "name": "http://{{url}}:18081/backend/dashboard/dashboards/{{dashboardId}}/module-widgets",
              "request": {
                "method": "POST",
                "header": [
                  {
                    "key": "Authorization",
                    "value": "{{oauth2}}"
                  },
                  {
                    "key": "Accept",
                    "value": "application/vnd.siren+json, application/json"
                  },
                  {
                    "key": "Content-Type",
                    "value": "application/json"
                  }
                ],
                "body": {
                  "mode": "raw",
                  "raw": ""
                },
                "url": {
                  "raw": "http://{{url}}:18081/backend/dashboard/dashboards/{{dashboardId}}/module-widgets",
                  "protocol": "http",
                  "host": [
                    "{{url}}"
                  ],
                  "port": "18081",
                  "path": [
                    "backend",
                    "dashboard",
                    "dashboards",
                    "{{dashboardId}}",
                    "module-widgets"
                  ],
                  "variable": [
                    {
                      "key": "dashboardId",
                      "value": "{{dashboardId}}"
                    }
                  ]
                }
              },
              "response": []
            },
            {
              "_postman_id": "2657417-7c340907-3d24-ace4-4871-f0d90b7143d8",
              "name": "http://{{url}}:18081/backend/dashboard/users/{{userId}}/dashboards",
              "request": {
                "method": "GET",
                "header": [
                  {
                    "key": "Authorization",
                    "value": "{{oauth2}}"
                  },
                  {
                    "key": "Accept",
                    "value": "application/vnd.siren+json, application/json"
                  },
                  {
                    "key": "Content-Type",
                    "value": "application/json"
                  }
                ],
                "body": {
                  "mode": "raw",
                  "raw": ""
                },
                "url": {
                  "raw": "http://{{url}}:18081/backend/dashboard/users/{{userId}}/dashboards",
                  "protocol": "http",
                  "host": [
                    "{{url}}"
                  ],
                  "port": "18081",
                  "path": [
                    "backend",
                    "dashboard",
                    "users",
                    "{{userId}}",
                    "dashboards"
                  ],
                  "variable": [
                    {
                      "key": "userId",
                      "value": "{{userId}}"
                    }
                  ]
                }
              },
              "response": []
            },
            {
              "_postman_id": "2657417-66a88dc3-7d7c-25ca-9461-1d3a9494c5b3",
              "name": "http://{{url}}:18081/backend/dashboard/users/{{userId}}/dashboards",
              "request": {
                "method": "POST",
                "header": [
                  {
                    "key": "Authorization",
                    "value": "{{oauth2}}"
                  },
                  {
                    "key": "Accept",
                    "value": "application/vnd.siren+json, application/json"
                  },
                  {
                    "key": "Content-Type",
                    "value": "application/json"
                  }
                ],
                "body": {
                  "mode": "raw",
                  "raw": ""
                },
                "url": {
                  "raw": "http://{{url}}:18081/backend/dashboard/users/{{userId}}/dashboards",
                  "protocol": "http",
                  "host": [
                    "{{url}}"
                  ],
                  "port": "18081",
                  "path": [
                    "backend",
                    "dashboard",
                    "users",
                    "{{userId}}",
                    "dashboards"
                  ],
                  "variable": [
                    {
                      "key": "userId",
                      "value": "{{userId}}"
                    }
                  ]
                }
              },
              "response": []
            }
          ],
          "_postman_isSubFolder": true
        }
      ]
    },
    {
      "_postman_id": "2657417-60773510-146a-1ff6-5fc1-af01c6c63677",
      "name": "Gateway",
      "description": null,
      "item": [
        {
          "_postman_id": "2657417-941022ba-5384-2029-c255-f2b628c8cd44",
          "name": "backend",
          "description": "Folder for backend",
          "item": [
            {
              "_postman_id": "2657417-1402fe90-05d1-2762-a281-6e5423a9fc25",
              "name": "Get gateway details",
              "request": {
                "method": "GET",
                "header": [
                  {
                    "key": "Authorization",
                    "value": "{{oauth2}}"
                  },
                  {
                    "key": "Accept",
                    "value": "application/vnd.siren+json, application/json"
                  },
                  {
                    "key": "Content-Type",
                    "value": "application/json"
                  }
                ],
                "body": {
                  "mode": "raw",
                  "raw": ""
                },
                "url": {
                  "raw": "http://{{url}}:18082/backend/gateway/gateways/{{gatewaySerial}}/details",
                  "protocol": "http",
                  "host": [
                    "{{url}}"
                  ],
                  "port": "18082",
                  "path": [
                    "backend",
                    "gateway",
                    "gateways",
                    "{{gatewaySerial}}",
                    "details"
                  ],
                  "variable": [
                    {
                      "key": "gatewaySerial",
                      "value": "{{gatewaySerial}}"
                    }
                  ]
                },
                "description": "Returns details of gateway by given gatewaySerial"
              },
              "response": []
            },
            {
              "_postman_id": "2657417-d2d5f1a7-64f8-268d-0d83-839a23edeaaa",
              "name": "Reboot a gateway",
              "request": {
                "method": "POST",
                "header": [
                  {
                    "key": "Authorization",
                    "value": "{{oauth2}}"
                  },
                  {
                    "key": "Accept",
                    "value": "application/vnd.siren+json, application/json"
                  },
                  {
                    "key": "Content-Type",
                    "value": "application/json"
                  }
                ],
                "body": {
                  "mode": "raw",
                  "raw": ""
                },
                "url": {
                  "raw": "http://{{url}}:18082/backend/gateway/gateways/{{gatewaySerial}}/details/reboot",
                  "protocol": "http",
                  "host": [
                    "{{url}}"
                  ],
                  "port": "18082",
                  "path": [
                    "backend",
                    "gateway",
                    "gateways",
                    "{{gatewaySerial}}",
                    "details",
                    "reboot"
                  ],
                  "variable": [
                    {
                      "key": "gatewaySerial",
                      "value": "{{gatewaySerial}}"
                    }
                  ]
                },
                "description": "Restart a gateway"
              },
              "response": []
            },
            {
              "_postman_id": "2657417-879c1a0b-820a-659e-5bf7-c9a874b59330",
              "name": "Unregister a gateway",
              "request": {
                "method": "POST",
                "header": [
                  {
                    "key": "Authorization",
                    "value": "{{oauth2}}"
                  },
                  {
                    "key": "Accept",
                    "value": "application/vnd.siren+json, application/json"
                  },
                  {
                    "key": "Content-Type",
                    "value": "application/json"
                  }
                ],
                "body": {
                  "mode": "raw",
                  "raw": ""
                },
                "url": {
                  "raw": "http://{{url}}:18082/backend/gateway/installations/{{installationId}}/gateways/{{gatewaySerial}}/unregister",
                  "protocol": "http",
                  "host": [
                    "{{url}}"
                  ],
                  "port": "18082",
                  "path": [
                    "backend",
                    "gateway",
                    "installations",
                    "{{installationId}}",
                    "gateways",
                    "{{gatewaySerial}}",
                    "unregister"
                  ],
                  "variable": [
                    {
                      "key": "gatewaySerial",
                      "value": "{{gatewaySerial}}"
                    },
                    {
                      "key": "installationId",
                      "value": "{{installationId}}"
                    }
                  ]
                },
                "description": "Decouples a gateway from an installation"
              },
              "response": []
            }
          ],
          "_postman_isSubFolder": true
        }
      ]
    },
    {
      "_postman_id": "2657417-ee2ba13a-4851-03c3-0848-568eec06d6a7",
      "name": "Activity Stream",
      "description": null,
      "item": [
        {
          "_postman_id": "2657417-883a6b24-2a7d-ea4c-69bf-e7593535c1c9",
          "name": "backend",
          "description": "Folder for backend",
          "item": [
            {
              "_postman_id": "2657417-51e31249-75a8-834c-7ef4-f877a34ca1ef",
              "name": "Get all data for the dashboard activities module of a user",
              "request": {
                "method": "GET",
                "header": [
                  {
                    "key": "Authorization",
                    "value": "{{oauth2}}"
                  },
                  {
                    "key": "Accept",
                    "value": "application/vnd.siren+json, application/json"
                  },
                  {
                    "key": "Content-Type",
                    "value": "application/json"
                  }
                ],
                "body": {
                  "mode": "raw",
                  "raw": ""
                },
                "url": {
                  "raw": "http://{{url}}:18085/backend/activity-stream/users/{{userId}}/dashboard-module-widget/activities",
                  "protocol": "http",
                  "host": [
                    "{{url}}"
                  ],
                  "port": "18085",
                  "path": [
                    "backend",
                    "activity-stream",
                    "users",
                    "{{userId}}",
                    "dashboard-module-widget",
                    "activities"
                  ],
                  "variable": [
                    {
                      "key": "userId",
                      "value": "{{userId}}"
                    }
                  ]
                }
              },
              "response": []
            }
          ],
          "_postman_isSubFolder": true
        }
      ]
    },
    {
      "_postman_id": "2657417-1c7e2508-2ae7-29c8-e129-aef7f03db950",
      "name": "User",
      "description": null,
      "item": [
        {
          "_postman_id": "2657417-de0f9d08-c5ce-7300-37c7-7743968950b4",
          "name": "Get user details for end customer",
          "request": {
            "method": "GET",
            "header": [
              {
                "key": "Authorization",
                "value": "{{oauth2}}"
              },
              {
                "key": "Accept",
                "value": "application/vnd.siren+json, application/json"
              },
              {
                "key": "Content-Type",
                "value": "application/json"
              }
            ],
            "body": {
              "mode": "raw",
              "raw": ""
            },
            "url": "http://{{url}}:18084/users/1234/details",
            "description": "Returns user details for end customer"
          },
          "response": []
        },
        {
          "_postman_id": "2657417-c3ea79a9-ee62-774a-306d-be3c406ea960",
          "name": "Get user details for heating installer",
          "request": {
            "method": "GET",
            "header": [
              {
                "key": "Authorization",
                "value": "{{oauth2}}"
              },
              {
                "key": "Accept",
                "value": "application/vnd.siren+json, application/json"
              },
              {
                "key": "Content-Type",
                "value": "application/json"
              }
            ],
            "body": {
              "mode": "raw",
              "raw": ""
            },
            "url": "http://{{url}}:18084/users/4567/details",
            "description": "Returns user details for heating installer"
          },
          "response": []
        },
        {
          "_postman_id": "2657417-64a771ad-c652-4eb1-7114-c189e1ac2342",
          "name": "Get user details for viessmann group",
          "request": {
            "method": "GET",
            "header": [
              {
                "key": "Authorization",
                "value": "{{oauth2}}"
              },
              {
                "key": "Accept",
                "value": "application/vnd.siren+json, application/json"
              },
              {
                "key": "Content-Type",
                "value": "application/json"
              }
            ],
            "body": {
              "mode": "raw",
              "raw": ""
            },
            "url": "http://{{url}}:18084/users/7890/details",
            "description": "Returns user details for viessmann group"
          },
          "response": []
        },
        {
          "_postman_id": "2657417-9728f47e-5daa-1523-f183-bb4d8e0372f6",
          "name": "Get users overview list",
          "request": {
            "method": "GET",
            "header": [
              {
                "key": "Authorization",
                "value": "{{oauth2}}"
              },
              {
                "key": "Accept",
                "value": "application/vnd.siren+json, application/json"
              },
              {
                "key": "Content-Type",
                "value": "application/json"
              }
            ],
            "body": {
              "mode": "raw",
              "raw": ""
            },
            "url": {
              "raw": "http://{{url}}:18084/users/{{userId}}/users?userGroup={{userGroup}}&searchTerm={{searchTerm}}&role={{role}}",
              "protocol": "http",
              "host": [
                "{{url}}"
              ],
              "port": "18084",
              "path": [
                "users",
                "{{userId}}",
                "users"
              ],
              "query": [
                {
                  "key": "userGroup",
                  "value": "{{userGroup}}"
                },
                {
                  "key": "searchTerm",
                  "value": "{{searchTerm}}"
                },
                {
                  "key": "role",
                  "value": "{{role}}"
                }
              ],
              "variable": [
                {
                  "key": "userId",
                  "value": "{{userId}}"
                }
              ]
            },
            "description": "Returns users overview for given user group as query paramater"
          },
          "response": []
        },
        {
          "_postman_id": "2657417-a318ecdc-da19-c5c3-1db1-bfcbc3f01d73",
          "name": "Get users overview list",
          "request": {
            "method": "POST",
            "header": [
              {
                "key": "Authorization",
                "value": "{{oauth2}}"
              },
              {
                "key": "Accept",
                "value": "application/vnd.siren+json, application/json"
              },
              {
                "key": "Content-Type",
                "value": "application/json"
              }
            ],
            "body": {
              "mode": "raw",
              "raw": ""
            },
            "url": {
              "raw": "http://{{url}}:18084/users/{{userId}}/users",
              "protocol": "http",
              "host": [
                "{{url}}"
              ],
              "port": "18084",
              "path": [
                "users",
                "{{userId}}",
                "users"
              ],
              "variable": [
                {
                  "key": "userId",
                  "value": "{{userId}}"
                }
              ]
            },
            "description": "Returns users overview for given user group in post payload"
          },
          "response": []
        }
      ]
    },
    {
      "_postman_id": "2657417-ac2c5399-7b6d-5120-7dfe-cdb0187b6902",
      "name": "Invitation",
      "description": null,
      "item": [
        {
          "_postman_id": "2657417-32e87a81-1566-ca67-a210-1e63646948a8",
          "name": "backend",
          "description": "Folder for backend",
          "item": [
            {
              "_postman_id": "2657417-0a7fbfa9-1174-ae94-9e22-612a08f5f26e",
              "name": "provide the invitation wizard steps (accept)",
              "request": {
                "method": "POST",
                "header": [
                  {
                    "key": "Authorization",
                    "value": "{{oauth2}}"
                  },
                  {
                    "key": "Accept",
                    "value": "application/vnd.siren+json, application/json"
                  },
                  {
                    "key": "Content-Type",
                    "value": "application/json"
                  }
                ],
                "body": {
                  "mode": "raw",
                  "raw": ""
                },
                "url": {
                  "raw": "http://{{url}}:18086/backend/invitations/accept/wizard/{{wizardId}}",
                  "protocol": "http",
                  "host": [
                    "{{url}}"
                  ],
                  "port": "18086",
                  "path": [
                    "backend",
                    "invitations",
                    "accept",
                    "wizard",
                    "{{wizardId}}"
                  ],
                  "variable": [
                    {
                      "key": "wizardId",
                      "value": "{{wizardId}}"
                    }
                  ]
                }
              },
              "response": []
            },
            {
              "_postman_id": "2657417-4deb97f6-5c8c-c605-dbd1-11367a06fe58",
              "name": "provide the invitation wizard steps (create)",
              "event": [
                {
                  "listen": "test",
                  "script": {
                    "type": "text/javascript",
                    "exec": [
                      "pm.test(\"Status code is 200\", function () {",
                      "    pm.response.to.have.status(200);",
                      "});"
                    ]
                  }
                }
              ],
              "request": {
                "method": "POST",
                "header": [
                  {
                    "key": "Authorization",
                    "value": "{{oauth2}}"
                  },
                  {
                    "key": "Accept",
                    "value": "application/vnd.siren+json, application/json"
                  },
                  {
                    "key": "Content-Type",
                    "value": "application/json"
                  }
                ],
                "body": {
                  "mode": "raw",
                  "raw": ""
                },
                "url": "http://{{url}}:18086/backend/invitations/create/wizard/{{wizardId}}"
              },
              "response": [
                {
                  "id": "2657417-7951ed4e-8ae0-eb0a-d93d-09c4f7437673",
                  "name": "create without new building",
                  "originalRequest": {
                    "method": "POST",
                    "header": [
                      {
                        "key": "Authorization",
                        "value": "{{oauth2}}"
                      },
                      {
                        "key": "Accept",
                        "value": "application/vnd.siren+json, application/json"
                      },
                      {
                        "key": "Content-Type",
                        "value": "application/json"
                      }
                    ],
                    "body": {
                      "mode": "raw",
                      "raw": "{\r\n  \"gatewayId\": \"7571381602763107\",\r\n  \"buildingId\": \"51\",\r\n  \"createNewBuilding\": false\r\n}"
                    },
                    "url": "http://{{url}}:18086/backend/invitations/create/wizard/0"
                  },
                  "status": "OK",
                  "code": 200,
                  "_postman_previewlanguage": "json",
                  "header": [
                    {
                      "key": "Connection",
                      "value": "keep-alive",
                      "name": "Connection",
                      "description": ""
                    },
                    {
                      "key": "Date",
                      "value": "Mon, 30 Oct 2017 13:32:02 GMT",
                      "name": "Date",
                      "description": ""
                    },
                    {
                      "key": "Transfer-Encoding",
                      "value": "chunked",
                      "name": "Transfer-Encoding",
                      "description": ""
                    },
                    {
                      "key": "cache-control",
                      "value": "no-cache",
                      "name": "cache-control",
                      "description": ""
                    },
                    {
                      "key": "content-encoding",
                      "value": "gzip",
                      "name": "content-encoding",
                      "description": ""
                    },
                    {
                      "key": "content-type",
                      "value": "application/vnd.siren+json",
                      "name": "content-type",
                      "description": ""
                    },
                    {
                      "key": "request-context",
                      "value": "appId=cid-v1:1849cb04-ccf5-4994-b5ff-79afe587e4a8,roleName=be-invitation",
                      "name": "request-context",
                      "description": ""
                    },
                    {
                      "key": "vary",
                      "value": "origin,accept-encoding",
                      "name": "vary",
                      "description": ""
                    }
                  ],
                  "cookie": [],
                  "responseTime": "133",
                  "body": "{\"class\":[\"invitation-wizard\"],\"properties\":{\"title\":\"Frontend-Invitations_INVITATION_WIZARD_TITLE\",\"progressionTitle\":\"Frontend-Invitations_PAGING_PREFIX\",\"progressionIndex\":\"1\",\"progressionTotal\":\"2\"},\"entities\":[{\"class\":[\"full-length\",\"text\"],\"rel\":[\"http://schema.viessmann.com/link-relations#field\"],\"properties\":{\"title\":\"Frontend-Invitations_GATEWAY_ID_TITLE\"}},{\"class\":[\"full-length\",\"input\"],\"rel\":[\"http://schema.viessmann.com/link-relations#field\"],\"properties\":{\"placeholder\":\"Frontend-Invitations_GATEWAY_ID_PLACEHOLDER\",\"value\":\"7571381602763107\",\"actionFieldName\":\"gatewayId\"}}],\"actions\":[{\"name\":\"next\",\"title\":\"NEXT\",\"method\":\"POST\",\"href\":\"http://52.169.79.192:18086/backend/invitations/create/wizard/1\",\"fields\":[{\"name\":\"gatewayId\",\"type\":\"text\",\"value\":\"7571381602763107\"}]}]}"
                }
              ]
            }
          ],
          "_postman_isSubFolder": true
        }
      ]
    },
    {
      "_postman_id": "2657417-9c0f7661-6d89-0f24-1a7f-a0e95366785d",
      "name": "Profile",
      "description": null,
      "item": [
        {
          "_postman_id": "2657417-a819d58f-ee55-d737-ebb7-5305b679dea9",
          "name": "backend",
          "description": "Folder for backend",
          "item": [
            {
              "_postman_id": "2657417-109c2338-62b4-9a6d-0770-969bb8eb5aa1",
              "name": "Get Example",
              "request": {
                "method": "GET",
                "header": [
                  {
                    "key": "Authorization",
                    "value": "{{oauth2}}"
                  },
                  {
                    "key": "Accept",
                    "value": "application/vnd.siren+json, application/json"
                  },
                  {
                    "key": "Content-Type",
                    "value": "application/json"
                  }
                ],
                "body": {
                  "mode": "raw",
                  "raw": ""
                },
                "url": {
                  "raw": "http://{{url}}:18088/backend/profile/example/{{exampleId}}?exampleQuery={{exampleQuery}}",
                  "protocol": "http",
                  "host": [
                    "{{url}}"
                  ],
                  "port": "18088",
                  "path": [
                    "backend",
                    "profile",
                    "example",
                    "{{exampleId}}"
                  ],
                  "query": [
                    {
                      "key": "exampleQuery",
                      "value": "{{exampleQuery}}"
                    }
                  ],
                  "variable": [
                    {
                      "key": "exampleId",
                      "value": "{{exampleId}}"
                    }
                  ]
                },
                "description": "Returns an example resource"
              },
              "response": []
            }
          ],
          "_postman_isSubFolder": true
        }
      ]
    },
    {
      "_postman_id": "2657417-bbd1470a-e6d1-8d3c-28ce-80b0889a3f40",
      "name": "ViCare",
      "description": null,
      "item": [
        {
          "_postman_id": "2657417-8f84b018-d0b2-607b-3107-2abcacc7d0cd",
          "name": "backend",
          "description": "Folder for backend",
          "item": [
            {
              "_postman_id": "2657417-d3d5f64b-d54a-8a30-2497-0736e0f49d0f",
              "name": "Set contact information",
              "request": {
                "method": "PUT",
                "header": [
                  {
                    "key": "Authorization",
                    "value": "{{oauth2}}"
                  },
                  {
                    "key": "Accept",
                    "value": "application/vnd.siren+json, application/json"
                  },
                  {
                    "key": "Content-Type",
                    "value": "application/json"
                  }
                ],
                "body": {
                  "mode": "raw",
                  "raw": "{\n\t\"phoneNumbers\": [\n\t\t{\n\t\t\t\"value\" : \"123456789\",\n\t\t\t\"favorite\": false\n\t\t},\n\t\t{\n\t\t\t\"value\" : \"987654321\",\n\t\t\t\"favorite\": true\n\t\t}\n\t],\n\t\"emails\": [\n\t\t{\n\t\t\t\"value\" : \"info@röhring.de\",\n\t\t\t\"favorite\": false\n\t\t},\n\t\t{\n\t\t\t\"value\" : \"christian@röhrig.de\",\n\t\t\t\"favorite\": true\n\t\t}\n\t]\n}"
                },
                "url": "http://{{url}}:18089/backend/vicare/installations/{{installationId}}/contractors/{{viCustomerNumber}}/contact",
                "description": "Returns list with heating contractors close to installation address. Query parameters: Option 1: installationId OR Option 2: longitude, latitude, countryCode, Optional and valid for both options: perimeter"
              },
              "response": []
            },
            {
              "_postman_id": "2657417-4a4b51ae-9b19-1a33-10e9-c1ee37e3f4f6",
              "name": "Get the chosen contractor",
              "request": {
                "method": "GET",
                "header": [
                  {
                    "key": "Authorization",
                    "value": "{{oauth2}}"
                  },
                  {
                    "key": "Accept",
                    "value": "application/vnd.siren+json, application/json"
                  },
                  {
                    "key": "Content-Type",
                    "value": "application/json"
                  }
                ],
                "body": {
                  "mode": "raw",
                  "raw": ""
                },
                "url": "http://{{url}}:18089/backend/vicare/installations/{{installationId}}/contractor"
              },
              "response": []
            },
            {
              "_postman_id": "2657417-aa94513f-6e71-7861-df6a-2dda964fea57",
              "name": "Remove the chosen contractor",
              "request": {
                "method": "DELETE",
                "header": [
                  {
                    "key": "Authorization",
                    "value": "{{oauth2}}"
                  },
                  {
                    "key": "Accept",
                    "value": "application/vnd.siren+json, application/json"
                  },
                  {
                    "key": "Content-Type",
                    "value": "application/json"
                  }
                ],
                "body": {
                  "mode": "raw",
                  "raw": ""
                },
                "url": "http://{{url}}:18089/backend/vicare/installations/{{installationId}}/contractor"
              },
              "response": []
            },
            {
              "_postman_id": "2657417-82070245-c6de-f6c4-f798-c3557941ae67",
              "name": "Get contractors",
              "request": {
                "method": "GET",
                "header": [
                  {
                    "key": "Authorization",
                    "value": "{{oauth2}}"
                  },
                  {
                    "key": "Accept",
                    "value": "application/vnd.siren+json, application/json"
                  },
                  {
                    "key": "Content-Type",
                    "value": "application/json"
                  }
                ],
                "body": {
                  "mode": "raw",
                  "raw": ""
                },
                "url": {
                  "raw": "http://{{url}}:18089/backend/vicare/contractors?installationId={{installationId}}",
                  "protocol": "http",
                  "host": [
                    "{{url}}"
                  ],
                  "port": "18089",
                  "path": [
                    "backend",
                    "vicare",
                    "contractors"
                  ],
                  "query": [
                    {
                      "key": "installationId",
                      "value": "{{installationId}}",
                      "equals": true
                    }
                  ]
                }
              },
              "response": []
            },
            {
              "_postman_id": "2657417-2a206122-1217-1c52-4e9d-e31dedab23ac",
              "name": "Set the chosen contractor",
              "request": {
                "method": "POST",
                "header": [
                  {
                    "key": "Authorization",
                    "value": "{{oauth2}}"
                  },
                  {
                    "key": "Accept",
                    "value": "application/vnd.siren+json, application/json"
                  },
                  {
                    "key": "Content-Type",
                    "value": "application/json"
                  }
                ],
                "body": {
                  "mode": "raw",
                  "raw": ""
                },
                "url": "http://{{url}}:18089/backend/vicare/installations/{{installationId}}/contractors/{{customerNumber}}/select"
              },
              "response": []
            },
            {
              "_postman_id": "2657417-866cf6de-2d2b-f750-d126-d7c94244646d",
              "name": "Grant or drop access for monitoring",
              "request": {
                "method": "POST",
                "header": [
                  {
                    "key": "Authorization",
                    "value": "{{oauth2}}"
                  },
                  {
                    "key": "Accept",
                    "value": "application/vnd.siren+json, application/json"
                  },
                  {
                    "key": "Content-Type",
                    "value": "application/x-www-form-urlencoded"
                  }
                ],
                "body": {
                  "mode": "urlencoded",
                  "urlencoded": [
                    {
                      "key": "access",
                      "value": "true",
                      "description": "",
                      "type": "text"
                    },
                    {
                      "key": "message",
                      "value": "This is a message",
                      "description": "",
                      "type": "text"
                    }
                  ]
                },
                "url": "http://{{url}}:18089/backend/vicare/installations/{{installationId}}/contractors/{{customerNumber}}/access"
              },
              "response": []
            },
            {
              "_postman_id": "2657417-4e011b2b-14aa-6542-6491-fa468934e442",
              "name": "Get invited family & friends",
              "request": {
                "method": "GET",
                "header": [
                  {
                    "key": "Authorization",
                    "value": "{{oauth2}}"
                  },
                  {
                    "key": "Accept",
                    "value": "application/vnd.siren+json, application/json"
                  },
                  {
                    "key": "Content-Type",
                    "value": "application/json"
                  }
                ],
                "body": {
                  "mode": "raw",
                  "raw": ""
                },
                "url": "http://{{url}}:18089/backend/vicare/installations/{{installationId}}/invitations"
              },
              "response": []
            }
          ],
          "_postman_isSubFolder": true
        }
      ]
    }
  ]
}